// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// CLDistanceMatrix
NumericMatrix CLDistanceMatrix(const NumericMatrix& mat);
RcppExport SEXP _OpenCLeaR_CLDistanceMatrix(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(CLDistanceMatrix(mat));
    return rcpp_result_gen;
END_RCPP
}
// CLWrapperDistanceMatrix
NumericMatrix CLWrapperDistanceMatrix(const NumericMatrix& mat);
RcppExport SEXP _OpenCLeaR_CLWrapperDistanceMatrix(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(CLWrapperDistanceMatrix(mat));
    return rcpp_result_gen;
END_RCPP
}
// SetKernelsPath
SEXP SetKernelsPath(String kernelsPath);
RcppExport SEXP _OpenCLeaR_SetKernelsPath(SEXP kernelsPathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type kernelsPath(kernelsPathSEXP);
    rcpp_result_gen = Rcpp::wrap(SetKernelsPath(kernelsPath));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OpenCLeaR_CLDistanceMatrix", (DL_FUNC) &_OpenCLeaR_CLDistanceMatrix, 1},
    {"_OpenCLeaR_CLWrapperDistanceMatrix", (DL_FUNC) &_OpenCLeaR_CLWrapperDistanceMatrix, 1},
    {"_OpenCLeaR_SetKernelsPath", (DL_FUNC) &_OpenCLeaR_SetKernelsPath, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_OpenCLeaR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
