# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CLDistanceMatrix <- function(mat) {
    .Call(`_OpenCLeaR_CLDistanceMatrix`, mat)
}

CLDistanceMatrixDirect <- function(mat) {
    .Call(`_OpenCLeaR_CLDistanceMatrixDirect`, mat)
}

CLDistanceMatrixWrapper <- function(mat) {
    .Call(`_OpenCLeaR_CLDistanceMatrixWrapper`, mat)
}

SetKernelsPath <- function(kernelsPath) {
    .Call(`_OpenCLeaR_SetKernelsPath`, kernelsPath)
}

