# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Activate OpenCL devive with maximum FLOPS
#'
#' Automatically chooses the device with maximum FLOPS.
#' @note This is the default activation method.
#' @export
ActivateDeviceWithMostFlops <- function() {
    invisible(.Call(`_OpenCLeaR_ActivateDeviceWithMostFlops`))
}

#' Activate OpenCL devive with maximum memory
#'
#' Automatically chooses the device with maximum memory.
#' @export
ActivateDeviceWithMostMemory <- function() {
    invisible(.Call(`_OpenCLeaR_ActivateDeviceWithMostMemory`))
}

#' Activate OpenCL devive by ID
#' @param id id of device, all devices will be shown on load ofthe
#'     library.
#' @export
ActivateDeviceWithID_Native <- function(id) {
    invisible(.Call(`_OpenCLeaR_ActivateDeviceWithID_Native`, id))
}

#' OpenCL asynchronous device activation routine to break Windows WDDM context lock
#' @export
ActivateDeviceWithID_Async <- function(id) {
    .Call(`_OpenCLeaR_ActivateDeviceWithID_Async`, id)
}

#' OpenCL initialization routine
#'
#' to be called via onLoad mechanism.
#' @export
InitCL <- function() {
    .Call(`_OpenCLeaR_InitCL`)
}

#' OpenCL initialization routine
#'
#' called via onLoad mechanism.
#' @param kernelsPath string, contains path to load OpenCL kernels from.
#' @export
SetKernelsPath <- function(kernelsPath) {
    invisible(.Call(`_OpenCLeaR_SetKernelsPath`, kernelsPath))
}

#' @export
IsOpenCLReady <- function() {
    .Call(`_OpenCLeaR_IsOpenCLReady`)
}

#' Schaltet die detaillierte OpenCL-Diagnose und Hardware-Tabellen im Terminal ein oder aus
#' @param state bool, TRUE zum Einschalten, FALSE zum Stummschalten
#' @export
ToggleOpenCLPrint <- function(state) {
    invisible(.Call(`_OpenCLeaR_ToggleOpenCLPrint`, state))
}

.GetActiveDeviceInfo_cpp <- function() {
    .Call(`_OpenCLeaR_GetActiveDeviceInfo`)
}

.is_device_bound_cpp <- function() {
    .Call(`_OpenCLeaR_is_device_bound`)
}

.GetDeviceList_cpp <- function() {
    .Call(`_OpenCLeaR_GetDeviceList`)
}

.GetKernelsPath_cpp <- function() {
    .Call(`_OpenCLeaR_GetKernelsPath`)
}

#' Get kernel code as seen by OpenCL
#'
#' @export
GetKernelCode <- function() {
    .Call(`_OpenCLeaR_GetKernelCode`)
}

.create_transient_device_cpp <- function(platform_id, device_id, kernels_path) {
    .Call(`_OpenCLeaR_create_transient_device_cpp`, platform_id, device_id, kernels_path)
}

.set_transient_device_path_cpp <- function(device_xptr, kernel_path) {
    invisible(.Call(`_OpenCLeaR_set_transient_device_path_cpp`, device_xptr, kernel_path))
}

